services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,qs
      - N8N_USER_MANAGEMENT_ENABLED=true
      - N8N_AUTH_EXCLUDE_ENDPOINTS=healthz
      # Configuración SMTP para enviar correos electrónicos
      - N8N_SMTP_HOST=smtp.gmail.com        # Cambia esto si usas otro servicio
      - N8N_SMTP_PORT=465                   # Cambia esto si usas otro puerto
      - N8N_SMTP_USER=system@bqbsa.com     # Tu correo electrónico
      - N8N_SMTP_PASS=bqbsa.com # La contraseña o clave de aplicación de tu cuenta
      - N8N_SMTP_SENDER_NAME="BQBSA"    # Nombre del remitente
      - N8N_SMTP_SENDER_EMAIL=system@bqbsa.com  # Correo electrónico del remitente
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    restart: unless-stopped

volumes:
  db-data:
